version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: config/app/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
  db:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  # ----------------------------------
  # pgAdminを動かすコンテナ
  # ----------------------------------
  pgadmin:
    image: dpage/pgadmin4:6.11
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
        - db
volumes:
  db-data:
  volume_pgadmin:
